AWSTemplateFormatVersion: "2010-09-09"
Description: A template for SSH open

Resources:
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-094125af156557ca2
      InstanceType: t3.nano
      SecurityGroupIds:
        - !Ref SecurityGroup
  
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          # CidrIp: 10.0.0.0/0
          CidrIp: 0.0.0.0/0
